[package]
name = "mintcash-bindings"
version = "0.1.0"
authors = ["Unorthodox Labs, LLC"]
edition = "2021"
description = "Bindings for CustomMsg and CustomQuery for the Mint Cash blockchain"
repository = "https://github.com/mint-cash/mintcash-bindings"
license = "Apache-2.0"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package.metadata.docs.rs]
features = [
    "stargate",
]

[features]
stargate = []

[dependencies]
cosmwasm-schema = "1.5"
cosmwasm-std = { version = "1.5", features = ["stargate"] }
schemars = "0.8"
serde = { version = "1.0", default-features = false, features = ["derive"] }
prost = "0.11"
mintcash-rust = { path = "../mintcash-rust" }